[build]
  command = "pip install -r requirements.txt"  # Ensure dependencies are installed
  functions = "functions"  # Netlify Functions folder (for Serverless functions)
  publish = "public"  # Optional, if you have frontend assets

[functions]
  runtime = "python"  # Enable Python for Netlify Functions

[[redirects]]
  from = "/logSliderData"  # URL to call the function
  to = "/.netlify/functions/ea_backend"  # Path to the Flask function
  status = 200